name: Bump version
on:
  pull_request:
    branches: ["master"]
    types: [closed]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: "./package.json, ./package-lock.json"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: steps.changelog.outputs.skipped != 'true'
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
